addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.3.2")
addSbtPlugin("io.crashbox"       % "sbt-gpg"      % "0.2.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.13")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.9.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.4.0")